#!/bin/bash

# Sets up test-app-pnpm-monorepo: produces the plugin tarball at the repo
# root, then `pnpm install` inside the workspace. The mobile app at
# apps/mobile/ depends on customerio-reactnative alongside packages/shared-cio-utils
# so that pnpm has to deduplicate and symlink the SDK across packages — the
# exact shape that surfaced the duplicate-pod bug in real customer monorepos.

set -e

SCRIPT_DIR="$(dirname "$0")"
source "$SCRIPT_DIR/utils.sh"

print_heading "Setting up test-app-pnpm-monorepo..."

print_blue "\nGenerating plugin tarball at repo root..."
"$SCRIPT_DIR/create-plugin-tarball.sh" "."

cd test-app-pnpm-monorepo

print_blue "\nInstalling dependencies with pnpm (workspace)..."
pnpm install

print_blue "\nRunning expo prebuild in apps/mobile..."
# WIP (inbox): `--no-install` because prebuild would otherwise run `pod install` before the CIO branch
# pins below are in the Podfile, and it fails resolving the unpublished CustomerIOMessagingInbox.
# Pods are installed explicitly after patching. Restore the plain `--clean` on native release.
pnpm --filter @cio-test/mobile exec expo prebuild --clean --no-install

# WIP (inbox): the app depends on the RN SDK from a git branch whose podspec needs
# `CustomerIOMessagingInbox`, and the native Visual Inbox is not published yet. Point the CIO pods at
# the native base feature branch. Applied here rather than committed because `ios/` is generated by
# `expo prebuild --clean` above, so a committed Podfile edit would be wiped every run.
# Android needs nothing: the RN library declares the snapshot repo and version itself, and this app's
# settings.gradle does not restrict repositories to settings-only.
# DELETE this block once the native inbox publishes.
CIO_IOS_BRANCH="${CIO_IOS_BRANCH:-feat/overlay-inbox}"
PODFILE="apps/mobile/ios/Podfile"
if [ -f "$PODFILE" ] && ! grep -q "install_non_production_ios_sdk_git_branch" "$PODFILE"; then
  print_blue "\nPinning CIO iOS pods to branch ${CIO_IOS_BRANCH} in ${PODFILE}..."
  python3 - "$PODFILE" "$CIO_IOS_BRANCH" <<'PY'
import re, sys
path, branch = sys.argv[1], sys.argv[2]
src = open(path).read()
header = (
    "# WIP (inbox): unreleased native Visual Inbox — see scripts/setup-test-app-pnpm-monorepo.sh\n"
    "require 'open-uri'\n"
    "IO.copy_stream(URI.open('https://raw.githubusercontent.com/customerio/customerio-ios/main/"
    "scripts/cocoapods_override_sdk.rb'), '/tmp/override_cio_sdk.rb')\n"
    "load '/tmp/override_cio_sdk.rb'\n\n"
)
# The helper is fetched from customerio-ios `main`, whose pod list does not include the inbox yet,
# so the inbox pod is added explicitly. Jist resolves on its own (CustomerIOMessagingInbox.podspec
# on the branch depends on the published `Jist 0.1.0`).
inject = (
    "\n  install_non_production_ios_sdk_git_branch(branch_name: '%s', is_app_extension: false, "
    "push_service: 'apn')\n"
    "  pod 'CustomerIOMessagingInbox', :git => 'https://github.com/customerio/customerio-ios.git', "
    ":branch => '%s'\n"
    "  pod 'CustomerIOTrackingMigration', :git => 'https://github.com/customerio/customerio-ios.git', "
    ":branch => '%s'\n" % (branch, branch, branch)
)
m = re.search(r"^target ['\"][^'\"]+['\"] do\n", src, re.M)
if not m:
    sys.exit("could not find a target block in the generated Podfile")
src = header + src[:m.end()] + inject + src[m.end():]
open(path, "w").write(src)
print("  Podfile patched")
PY
fi

# Pods are installed here rather than by prebuild, so the branch pins above are in place first.
if [ -f "$PODFILE" ]; then
  print_blue "\nInstalling pods in apps/mobile/ios..."
  (cd apps/mobile/ios && pod install)
fi

cd ..

print_success "✅ test-app-pnpm-monorepo setup complete."
