export function testAppPath(): string;
export function testAppName(): string;
export function getTestAppAndroidPackageName(): string;
export function getTestAppAndroidPackagePath(): string;
export function getTestAppAndroidJavaSourcePath(): string;
export function getExpoVersion(): string;
export function isExpoVersion53OrHigher(): boolean;
export function isExpoVersionAtLeast(targetVersion: string): boolean;
export function isExpoVersionLatest(): boolean;
export function getFixturePath(area: string, name: string): string;
