version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "customerio/mobile"
    commit-message:
      prefix: "chore"
      include: "scope"
