version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "hourly"
    target-branch: "cleaning/dependabot"
    commit-message:
      prefix: "chore"
      include: "scope"
