name: Deploy plugin npm

# If deployment tries to push to npm and then push git tags
# when git tag deployment fails, you cannot push to npm again
# as it doesn't allow overwriting previously deployed artifacts. Deploy
# tag first, then deploy to npm on successful tag deployment.
on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci

      - name: Deploy to npm
        run: ./scripts/deploy-code.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Notify team of successful deployment
        uses: slackapi/slack-github-action@v1.18.0
        if: ${{ success() }}
        with:
          # Use block kit to format the Slack message: https://app.slack.com/block-kit-builder
          payload: |
            {
              "text": "Expo plugin deployed to npm",
              "username": "Expo deployment bot",
              "icon_url": "https://logos-download.com/wp-content/uploads/2021/01/Expo_Logo.png",
              "channel": "#mobile-deployments",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Expo* plugin deployed to npm! (deployment step 2 of 2)"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Version ${{ github.event.release.tag_name }}*\n\nExpo plugin deployment progress:\n ~1. <https://github.com/${{github.repository}}/releases/tag/${{ github.event.release.tag_name }}|create git tag>~\n~2. deploy to npm~\n\n"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Notify team of failure
        uses: slackapi/slack-github-action@v1.18.0
        if: ${{ failure() }} # only run this if any previous step failed
        with:
          # Use block kit to format the Slack message: https://app.slack.com/block-kit-builder
          payload: |
            {
              "text": "Expo plugin deployment failure",
              "username": "Expo deployment bot",
              "icon_url": "https://logos-download.com/wp-content/uploads/2021/01/Expo_Logo.png",
              "channel": "#mobile-deployments",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Expo* plugin deployment :warning: failure :warning:"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Expo plugin failed deployment during step *deploy to npm*. View <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|CI server logs> to learn why and fix the issue. <https://github.com/customerio/mobile/blob/main/GIT-WORKFLOW.md|Learn more about the deployment process and how to fix errors>."
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
